<?php

namespace MarmitonBundle\Repository;

/**
 * ReceiptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptsRepository extends \Doctrine\ORM\EntityRepository
{
}
