<?php

namespace MarmitonBundle\Repository;

/**
 * TypePlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlatRepository extends \Doctrine\ORM\EntityRepository
{
}
